apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pytorchdev.yaml
  - pytorchtrain.yaml
  - openssh/openssh.yaml
  - openssh/configmap.yaml
  - openssh/secrets.yaml
  - sharedpvc.yaml
  - gateway.yaml
  - tcproute.yaml
  - seedlab-pytorch.yaml
